apps/hotelapp/urls.py
from django.conf.urls import url
from apps.hotelapp.views import Index, UsuarioCreate, UsuarioList, UsuarioDelete
from apps.hotelapp.views import UsuarioUpdate, UsuarioShow, search, SucursalCreate
from apps.hotelapp.views import SucursalList, SucursalDelete, SucursalUpdate, SucursalShow
from apps.hotelapp.views import search_sucursal

urlpatterns = [
    url(r'^$', Index.as_view(), name='index'),
    url(r'^nuevo/', UsuarioCreate.as_view(), name='usuario_crear'),
    url(r'^listar', UsuarioList.as_view(), name='usuario_listar'),
    url(r'^eliminar/(?P<pk>\d+)/$', UsuarioDelete.as_view(), name='usuario_eliminar'),
    url(r'^editar/(?P<pk>\d+)/$', UsuarioUpdate.as_view(), name='usuario_editar'),
    url(r'^mostrar/(?P<pk>\d+)/$', UsuarioShow.as_view(), name='usuario_mostrar'),
    url(r'^buscar/$', search, name='usuario_buscar'),
    url(r'^nuevasuc/', SucursalCreate.as_view(), name='sucursal_crear'),
    url(r'^listasuc', SucursalList.as_view(), name='sucursal_listar'),
    url(r'^eliminasuc/(?P<pk>\d+)/$', SucursalDelete.as_view(), name='sucursal_eliminar'),
    url(r'^editasuc/(?P<pk>\d+)/$', SucursalUpdate.as_view(), name='sucursal_editar'),
    url(r'^muestrasuc/(?P<pk>\d+)/$', SucursalShow.as_view(), name='sucursal_mostrar'),
    url(r'^buscar_sucursal/$', search_sucursal, name='sucursal_buscar'),
]

hotelapp/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^usuarios/', include('apps.hotelapp.urls', namespace='usuarios')),
    url(r'^sucursales/', include('apps.hotelapp.urls', namespace='sucursales'))
]

apps/hotelapp/models.py
from django.db import models

# Create your models here.
class Sucursal(models.Model):
	id = models.AutoField(primary_key=True)
	nombre = models.CharField(max_length=20)

	def __str__(self):
		return '{}'.format(self.nombre)

class Usuario(models.Model):
	id = models.AutoField(primary_key=True)
	nombres = models.CharField(max_length=50)
	apellidos = models.CharField(max_length=50)
	fecha_nacimiento = models.DateField()
	email = models.CharField(max_length=50)
	hotel_hospedaje = models.ForeignKey(Sucursal, null=True, blank=True, on_delete=models.CASCADE)
	habitacion = models.CharField(max_length=50)

apps/hotelapp/forms.py
from django import forms
from apps.hotelapp.models import Usuario, Sucursal

class UsuarioForm(forms.ModelForm):
	class Meta:
		model = Usuario
		fields = [
			'nombres',
			'apellidos',
			'fecha_nacimiento',
			'email',
			'hotel_hospedaje',
			'habitacion'
		]

		labels = {
			'nombres': 'Nombres',
			'apellidos': 'Apellidos',
			'fecha_nacimiento': 'Fecha de Nacimiento',
			'email': 'Correo Electronico',
			'hotel_hospedaje': 'Hotel',
			'habitacion': 'Habitacion'
		}

		widgets = {
			'nombres': forms.TextInput(attrs={'class':'form-control'}),
			'apellidos': forms.TextInput(attrs={'class':'form-control'}),
			'fecha_nacimiento': forms.TextInput(attrs={'class':'form-control'}),
			'email': forms.TextInput(attrs={'class':'form-control'}),
			'hotel_hospedaje': forms.Select(attrs={'class':'form-control'}),
			'habitacion': forms.TextInput(attrs={'class':'form-control'}),
		}


class SucursalForm(forms.ModelForm):
	class Meta:
		model = Sucursal
		fields = [
			'nombre'
		]

		labels = {
			'nombre': 'Nombre'
		}

		widgets = {
			'nombre': forms.TextInput(attrs={'class':'form-control'})
		}

apps/hotelapp/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView, DeleteView, UpdateView
from django.views.generic.base import TemplateView
from django.core.urlresolvers import reverse_lazy
from django.views.generic.detail import DetailView

from apps.hotelapp.models import Usuario
from apps.hotelapp.forms import UsuarioForm
from apps.hotelapp.filters import UsuarioFilter

from apps.hotelapp.models import Sucursal
from apps.hotelapp.forms import SucursalForm
from apps.hotelapp.filters import SucursalFilter

# Create your views here.

class Index(TemplateView):
    template_name = "home.html"

class UsuarioCreate(CreateView):
	model = Usuario
	form_class = UsuarioForm
	template_name = 'hotelapp/usuario_form.html'
	success_url = reverse_lazy('usuarios:usuario_listar')

class UsuarioList(ListView):
	queryset = Usuario.objects.order_by('id')
	template_name = 'hotelapp/usuarios_list.html'
	paginate_by = 5

class UsuarioUpdate(UpdateView):
	model = Usuario
	form_class = UsuarioForm
	template_name = 'hotelapp/usuario_form.html'
	success_url = reverse_lazy('usuarios:usuario_listar')

class UsuarioDelete(DeleteView):
	model = Usuario
	template_name = 'hotelapp/usuario_delete.html'
	success_url = reverse_lazy('usuarios:usuario_listar')

class UsuarioShow(DetailView):
	model = Usuario
	template_name = 'hotelapp/usuario_show.html'


class SucursalCreate(CreateView):
	model = Sucursal
	form_class = SucursalForm
	template_name = 'hotelapp/sucursal_form.html'
	success_url = reverse_lazy('sucursales:sucursal_listar')

class SucursalList(ListView):
	queryset = Sucursal.objects.order_by('id')
	template_name = 'hotelapp/sucursal_list.html'
	paginate_by = 5

class SucursalUpdate(UpdateView):
	model = Sucursal
	form_class = SucursalForm
	template_name = 'hotelapp/sucursal_form.html'
	success_url = reverse_lazy('sucursales:sucursal_listar')

class SucursalDelete(DeleteView):
	model = Sucursal
	template_name = 'hotelapp/sucursal_delete.html'
	success_url = reverse_lazy('sucursales:sucursal_listar')

class SucursalShow(DetailView):
	model = Sucursal
	template_name = 'hotelapp/sucursal_show.html'

def search(request):
	usuario_list = Usuario.objects.all()
	usuario_filter = UsuarioFilter(request.GET, queryset=usuario_list)
	return render(request, 'hotelapp/usuario_list2.html', {'filter': usuario_filter})

def search_sucursal(request):
	sucursal_list = Sucursal.objects.all()
	sucursal_filter = SucursalFilter(request.GET, queryset=sucursal_list)
	return render(request, 'hotelapp/sucursal_list2.html', {'filter': sucursal_filter})

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">

	{% block extrastatic %}
	{% endblock %}

	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<title>{% block title %}Document {% endblock %}</title>
</head>
<body>
<div class="container">

	{% block navbar %}
		<div class="bs-docs-section clearfix">
		    <div class="row">
		        <div class="col-lg-12">
		            <div class="bs-component">
		            	<nav class="navbar navbar-default">
		                	<div class="container-fluid">
		                  		<div class="navbar-header">
		                    		<a class="navbar-brand" href="#">Home</a>
		                  		</div>
		                  	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		                    	<ul class="nav navbar-nav">
		                      		<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Usuarios <span class="caret"></span></a>
				                        <ul class="dropdown-menu" role="menu">
				                        	<li><a href="{% url 'usuarios:usuario_crear' %}">Registrar</a></li>
				                        	<li><a href="{% url 'usuarios:usuario_listar' %}">Listar</a></li>
				                        	<li><a href="{% url 'usuarios:usuario_buscar' %}">Buscar/Filtrar</a></li>
				                        </ul>
		                      		</li>
															<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Sucursales <span class="caret"></span></a>
				                        <ul class="dropdown-menu" role="menu">
				                        	<li><a href="{% url 'sucursales:sucursal_crear' %}">Registrar</a></li>
				                        	<li><a href="{% url 'sucursales:sucursal_listar' %}">Listar</a></li>
				                        	<li><a href="{% url 'sucursales:sucursal_buscar' %}">Buscar/Filtrar</a></li>
				                        </ul>
		                      		</li>
		                    	</ul>
		                    	<ul class="nav navbar-nav navbar-right">
		                        	<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Opciones<span class="caret"></span></a>
		                        		<ul class="dropdown-menu" role="menu">
		                          			<li><a href="#">Salir</a></li>
		                        		</ul>
		                      		</li>
		                    	</ul>
		                    </div>
		                </div>
		            </nav>
		        </div>
           	</div>
        </div>
    </div>

	{% endblock %}


	{% block content %}
	<h4>	Bloque de contenido		</h4>
	{% endblock %}


	{% block footer %}
	{% endblock%}
</div>
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>

	{% block extrajs %}
	{% endblock %}


</body>
</html>

templates/hotelapp/index.html
<p>fuck</p>

templates/hotelapp/sucursal_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<h3>¿Desea eliminar el registro de {{ object.nombre }}?</h3>
	<button class="btn btn-danger" type="submit">Sí, eliminar</button>
	<a class= "btn btn-default" href="{% url 'sucursales:sucursal_listar' %}">Cancelar</a>
</form>
{% endblock %}

templates/hotelapp/sucursal_form.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button class="btn btn-success" type="submit">Guardar</button>
	<a class= "btn btn-primary" href="{% url 'sucursales:sucursal_listar' %}">Cancelar</a>
</form>
{% endblock %}

templates/hotelapp/sucursal_list.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-bordered">
	<thead>
		<tr>
			<td>#</td>
			<td>Nombre</td>
			<td>Acciones</td>
		</tr>

	</thead>
	<tbody>
		{% if object_list %}
		{% for sucursal in object_list %}
		<tr>
			<td>{{ sucursal.id }}</td>
			<td>{{ sucursal.nombre }}</td>
			<td>
				<a class="btn btn-primary" href="{% url 'sucursales:sucursal_mostrar' sucursal.id %}">Ver</a>
				<a class="btn btn-primary" href="{% url 'sucursales:sucursal_editar' sucursal.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'sucursales:sucursal_eliminar' sucursal.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}

		{% else %}
		<h1>No hay registros de sucursales</h1>
		{% endif %}
	</tbody>
</table>
<ul class="pager">
	<li>
		{% if page_obj.has_previous %}
       	 <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
		{% endif %}
        </li>
	<li>
		{% if page_obj.has_next %}
     	 <a href="?page={{ page_obj.next_page_number }}">Next</a>
    	{% endif %}
    </li>
</ul>
{% endblock%}

templates/hotelapp/sucursal_list2.html
{% extends 'base/base.html' %}

{% block content %}
	<h4>Filtrar por:</h4>
	<form method="get">
	<p>
	Nombre: &nbsp{{ filter.form.nombre }} &nbsp;
	<button class="btn btn-success" type="submit">Filtrar</button>
	</p>
	</form>
	<table class="table table-bordered">
	<thead>
		<tr>
			<td>Id</td>
			<td>Nombre</td>
			<td>Acciones</td>
		</tr>

	</thead>
	<tbody>
		{% if filter.qs %}
		{% for sucursal in filter.qs %}
		<tr>
			<td>{{ sucursal.id }}</td>
			<td>{{ sucursal.nombre }}</td>
			<td>
				<a class="btn btn-primary" href="{% url 'sucursales:sucursal_mostrar' sucursal.id %}">Ver</a>
				<a class="btn btn-primary" href="{% url 'sucursales:sucursal_editar' sucursal.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'sucursales:sucursal_eliminar' sucursal.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}

		{% else %}
		<h1>No hay registros de sucursales</h1>
		{% endif %}
	</tbody>
</table>
<ul class="pager">
	<li>
		{% if page_obj.has_previous %}
       	 <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
		{% endif %}
        </li>
	<li>
		{% if page_obj.has_next %}
     	 <a href="?page={{ page_obj.next_page_number }}">Next</a>
    	{% endif %}
    </li>
</ul>

{% endblock %}

templates/hotelapp/sucursal_show.html
{% extends 'base/base.html' %}

{% block content %}

<p><strong>Id: </strong>{{ object.id }} </p>
<p><strong>Nombres: </strong>{{ object.nombre }} </p>

<a class= "btn btn-success" href="{% url 'sucursales:sucursal_listar' %}">Ok</a>
<a class= "btn btn-primary" href="{% url 'sucursales:sucursal_editar' object.id%}">Editar</a>
<a class="btn btn-danger" href="{% url 'sucursales:sucursal_eliminar' object.id %}">Eliminar</a>

{% endblock %}

templates/hotelapp/usuario_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<h3>¿Desea eliminar el registro de {{ object.nombres }}?</h3>
	<button class="btn btn-danger" type="submit">Sí, eliminar</button>
	<a class= "btn btn-default" href="{% url 'usuarios:usuario_listar' %}">Cancelar</a>
</form>
{% endblock %}

templates/hotelapp/usuario_form.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button class="btn btn-success" type="submit">Guardar</button>
	<a class= "btn btn-primary" href="{% url 'usuarios:usuario_listar' %}">Cancelar</a>
</form>
{% endblock %}

templates/hotelapp/usuario_list.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-bordered">
	<thead>
		<tr>
			<td>#</td>
			<td>Nombres</td>
			<td>Apellidos</td>
			<td>Fecha de Nacimiento</td>
			<td>Email</td>
			<td>Hotel</td>
			<td>Habitacion</td>
			<td>Acciones</td>
		</tr>

	</thead>
	<tbody>
		{% if object_list %}
		{% for usuario in object_list %}
		<tr>
			<td>{{ usuario.id }}</td>
			<td>{{ usuario.nombres }}</td>
			<td>{{ usuario.apellidos }}</td>
			<td>{{ usuario.fecha_nacimiento }}</td>
			<td>{{ usuario.email }}</td>
			<td>{{ usuario.hotel_hospedaje }}</td>
			<td>{{ usuario.habitacion }}</td>
			<td>
				<a class="btn btn-primary" href="{% url 'usuarios:usuario_mostrar' usuario.id %}">Ver</a>
				<a class="btn btn-primary" href="{% url 'usuarios:usuario_editar' usuario.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'usuarios:usuario_eliminar' usuario.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}

		{% else %}
		<h1>No hay registros de usuarios</h1>
		{% endif %}
	</tbody>
</table>
<ul class="pager">
	<li>
		{% if page_obj.has_previous %}
       	 <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
		{% endif %}
        </li>
	<li>
		{% if page_obj.has_next %}
     	 <a href="?page={{ page_obj.next_page_number }}">Next</a>
    	{% endif %}
    </li>
</ul>
{% endblock%}

templates/hotelapp/usuario_list2.html
{% extends 'base/base.html' %}

{% block content %}
	<h4>Filtrar por:</h4>
	<form method="get">
	<p>
	Nombre: &nbsp{{ filter.form.nombres }} &nbsp
	Apellido: &nbsp {{ filter.form.apellidos }} &nbsp
	Email: &nbsp{{ filter.form.email }} &nbsp;&nbsp;
	<button class="btn btn-success" type="submit">Filtrar</button>
	</p>
	</form>
	<table class="table table-bordered">
	<thead>
		<tr>
			<td>id</td>
			<td>Nombres</td>
			<td>Apellidos</td>
			<td>Fecha de Nacimiento</td>
			<td>Email</td>
			<td>Hotel</td>
			<td>Acciones</td>
		</tr>

	</thead>
	<tbody>
		{% if filter.qs %}
		{% for usuario in filter.qs %}
		<tr>
			<td>{{ usuario.id }}</td>
			<td>{{ usuario.nombres }}</td>
			<td>{{ usuario.apellidos }}</td>
			<td>{{ usuario.fecha_nacimiento }}</td>
			<td>{{ usuario.email }}</td>
			<td>{{ usuario.hotel_hospedaje }}</td>
			<td>
				<a class="btn btn-primary" href="{% url 'usuarios:usuario_mostrar' usuario.id %}">Ver</a>
				<a class="btn btn-primary" href="{% url 'usuarios:usuario_editar' usuario.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'usuarios:usuario_eliminar' usuario.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}

		{% else %}
		<h1>No hay registros de usuarios</h1>
		{% endif %}
	</tbody>
</table>
<ul class="pager">
	<li>
		{% if page_obj.has_previous %}
       	 <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
		{% endif %}
        </li>
	<li>
		{% if page_obj.has_next %}
     	 <a href="?page={{ page_obj.next_page_number }}">Next</a>
    	{% endif %}
    </li>
</ul>

{% endblock %}

templates/hotelapp/usuario_show.html
{% extends 'base/base.html' %}

{% block content %}

<p><strong>Id: </strong>{{ object.id }} </p>
<p><strong>Nombres: </strong>{{ object.nombres }} </p>
<p><strong>Apellidos: </strong>{{ object.apellidos }} </p>
<p><strong>Fecha de Nacimiento: </strong>{{ object.fecha_nacimiento }} </p>
<p><strong>Email: </strong>{{ object.email }} </p>
<p><strong>Hotel: </strong>{{ object.hotel_hospedaje }} </p>

<a class= "btn btn-success" href="{% url 'usuarios:usuario_listar' %}">Ok</a>
<a class= "btn btn-primary" href="{% url 'usuarios:usuario_editar' object.id%}">Editar</a>
<a class="btn btn-danger" href="{% url 'usuarios:usuario_eliminar' object.id %}">Eliminar</a>

{% endblock %}